[theme]
base = "dark"
primaryColor = "#F97316"
backgroundColor = "#080E18"
secondaryBackgroundColor = "#0E1726"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
